name: RSS to uwuzu
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # 最新のNode.js環境を強制的に使う設定
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4 # v4のままでも上のenv設定があれば動きます
      - name: Set up Python
        uses: actions/setup-python@v5 # ここをv5に更新
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Bot
        env:
          UWUZU_TOKEN: ${{ secrets.UWUZU_TOKEN }}
        run: python bot.py
      - name: Commit and Push (Save progress)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add last_link.txt
          git commit -m "Update last posted link" || exit 0
          git push
